# ─────────────────────────────────────────────────────────────────────────────
# IRIS — Executive Memorandum Page
# Auto-generated policy memorandum addressed to the CBK Governor and MPC.
# Updates every time the models run with fresh analysis.
# ─────────────────────────────────────────────────────────────────────────────

import streamlit as st
from datetime import datetime


def render(iris: dict):
    score          = iris["iris_score"]["iris_score"]
    classification = iris["classification"]
    signals        = iris["signals"]
    models         = iris["model_results"]
    latest         = iris["latest"]
    colour         = iris["iris_score"]["regime_colour"]
    regime         = classification["regime"]
    emoji          = classification["regime_emoji"]
    loaded_at      = iris.get("loaded_at", datetime.now())

    inf_val = latest.get("inflation",     {}).get("value")
    ir_val  = latest.get("interest_rate", {}).get("value")
    real_rate = (ir_val - inf_val) if (inf_val is not None and ir_val is not None) else None

    vecm   = models.get("vecm",   {})
    garch  = models.get("garch",  {})
    fevd   = models.get("fevd",   {})
    regime_m = models.get("regime", {})
    irf    = models.get("irf",    {})
    corr   = models.get("correlations", {})

    st.markdown("## 📋 Executive Memorandum")
    st.markdown(f"""
    <div style='background:#F5F5F5; border:1px solid #CCCCCC; border-radius:6px;
                padding:0.6rem 1rem; margin-bottom:1rem; font-size:0.82rem; color:#555;'>
        This memorandum is auto-generated by IRIS on every model run.
        It translates all model outputs into a policy-ready document.
        Generated: {loaded_at.strftime('%d %B %Y at %H:%M')}
    </div>
    """, unsafe_allow_html=True)

    # ── Memo header ───────────────────────────────────────────────────────────
    st.markdown(f"""
    <div style='background:linear-gradient(135deg,#003300,#006400); color:white;
                padding:1.5rem 2rem; border-radius:10px; margin-bottom:1.5rem;'>
        <div style='font-size:0.8rem; color:#C5A028; font-weight:bold; letter-spacing:2px;'>
            CENTRAL BANK OF KENYA — POLICY ANALYSIS UNIT
        </div>
        <div style='font-size:1.6rem; font-weight:bold; margin:0.5rem 0;'>
            EXECUTIVE MEMORANDUM
        </div>
        <div style='font-size:0.9rem; color:#AAFFAA;'>
            IRIS Intelligent Risk Integration System — Automated Policy Brief
        </div>
        <div style='margin-top:1rem; display:flex; gap:2rem; font-size:0.82rem;'>
            <div><b>TO:</b> H.E. The Governor, CBK &amp; Members, MPC</div>
            <div><b>FROM:</b> Policy Analysis Unit</div>
            <div><b>DATE:</b> {loaded_at.strftime('%d %B %Y')}</div>
            <div><b>REF:</b> IRIS/MPC/{loaded_at.strftime('%Y/%m')}/AUTO</div>
        </div>
        <div style='margin-top:0.5rem; font-size:0.82rem;'>
            <b>CLASSIFICATION:</b>
            <span style='color:#FFAAAA;'>SIMULATED — EDUCATIONAL USE ONLY</span>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # ── IRIS Risk headline ─────────────────────────────────────────────────────
    st.markdown(f"""
    <div style='background:{colour}18; border:2px solid {colour};
                border-radius:8px; padding:1rem 1.5rem; margin-bottom:1.2rem;'>
        <div style='font-size:1rem; font-weight:bold; color:{colour};'>
            IRIS COMPOSITE RISK ASSESSMENT
        </div>
        <div style='font-size:2rem; font-weight:bold; color:{colour}; margin:0.3rem 0;'>
            {emoji} {regime} — {score:.1f} / 100
        </div>
        <div style='font-size:0.88rem; color:#333;'>
            {classification.get("description", "")}
        </div>
        <div style='margin-top:0.6rem; padding:0.5rem; background:white;
                    border-radius:4px; font-size:0.85rem; color:#555; font-style:italic;'>
            {classification.get("plain_english", "")}
        </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Audience selector ──────────────────────────────────────────────────────
    memos    = iris.get("memos", {})
    audience = st.radio(
        "Select Audience",
        ["🏦 Governor", "📊 MPC", "🇰🇪 Wananchi"],
        horizontal=True,
    )

    memo_key = {"🏦 Governor": "governor", "📊 MPC": "mpc", "🇰🇪 Wananchi": "wananchi"}.get(audience, "mpc")
    memo     = memos.get(memo_key, {})

    if memo and not memo.get("error"):
        # PDF download button
        from utils.exporter import export_memo_to_pdf, get_pdf_download_name
        try:
            pdf_bytes = export_memo_to_pdf(memo)
            st.download_button(
                label="⬇️ Download as PDF",
                data=pdf_bytes,
                file_name=get_pdf_download_name(memo.get("type", "MEMO")),
                mime="application/pdf",
                use_container_width=False,
            )
        except Exception as e:
            st.caption(f"PDF export unavailable: {e}")

        # Render memo sections
        for section in memo.get("sections", []):
            colour = memo.get("colour", "#006400")
            st.markdown(f"""
            <div style='background:{colour}; color:white; font-weight:bold;
                        padding:0.5rem 1rem; border-radius:4px; margin:1rem 0 0.4rem 0;
                        font-size:0.9rem;'>
                {section["title"]}
                {"&nbsp;&nbsp;|&nbsp;&nbsp;" + section.get("swahili","") if section.get("swahili") else ""}
            </div>
            """, unsafe_allow_html=True)

            body = section.get("body", "")
            for para in body.split("\n\n"):
                if para.strip():
                    st.markdown(para.strip())

            if section.get("advice"):
                st.info(f"💡 {section['advice']}")

            if section.get("highlight"):
                st.markdown(f"""
                <div style='background:{section.get("highlight_colour","#006400")}22;
                            border-left:5px solid {section.get("highlight_colour","#006400")};
                            padding:1rem; border-radius:6px; margin:0.5rem 0;'>
                    {body[:400]}
                </div>
                """, unsafe_allow_html=True)
    else:
        st.error(f"Memo generation error: {memo.get('error', 'Unknown error')}")
        

    # ── Section 1: Current Situation ──────────────────────────────────────────
    st.markdown("### 1. Current Monetary Policy Situation")

    situation_text = f"""
    As of {loaded_at.strftime('%B %Y')}, Kenya's key monetary indicators are as follows:

    - **Inflation:** {f"{inf_val:.2f}%" if inf_val else "N/A"} — {'**above** the CBK target band of 2.5-7.5%' if inf_val and inf_val > 7.5 else '**within** the CBK target band of 2.5-7.5%'}
    - **CBK Interest Rate:** {f"{ir_val:.2f}%" if ir_val else "N/A"}
    - **Real Interest Rate:** {f"{real_rate:.2f}%" if real_rate is not None else "N/A"} — {'**positive**: savers are earning above inflation' if real_rate and real_rate > 0 else '**negative**: savers are losing purchasing power in real terms'}
    - **IRIS Risk Score:** {score:.1f}/100 ({emoji} {regime})
    - **Primary Risk Driver:** {classification.get("dominant_driver", "N/A")}
    """
    st.markdown(situation_text)

    # ── Section 2: Model Findings ─────────────────────────────────────────────
    st.markdown("### 2. Structural Model Findings")

    findings = [
        ("Cointegration & Long-Run Relationship", models.get("cointegration", {}).get("plain_english", "N/A")),
        ("VECM — Policy Character",               vecm.get("policy_plain", "N/A")),
        ("VECM — Long-Run Equation",              vecm.get("lr_plain", "N/A")),
        ("VECM — Correction Half-Life",           vecm.get("half_life_plain", "N/A")),
        ("Impulse Response — Transmission Lag",   irf.get("transmission_plain", "N/A")),
        ("Impulse Response — Price Puzzle",       irf.get("price_puzzle_plain", "N/A")),
        ("FEVD — Policy Effectiveness",           fevd.get("policy_plain", "N/A")),
        ("FEVD — Supply-Side Dominance",          fevd.get("supply_plain", "N/A")),
        ("GARCH — Current Volatility Risk",       garch.get("garch_risk_plain", "N/A")),
        ("GARCH — Persistence",                   garch.get("persistence_plain", "N/A")),
        ("Regime — Current Status",               regime_m.get("regime_plain", "N/A")),
        ("Regime — Persistence",                  regime_m.get("persistence_plain", "N/A")),
        ("Correlations — Fisher Effect",          corr.get("fisher_plain", "N/A")),
        ("Correlations — Lead-Lag Structure",     corr.get("lead_lag_plain", "N/A")),
    ]

    for title, text in findings:
        if text and text != "N/A":
            st.markdown(f"""
            <div style='border-left:3px solid #006400; padding:0.5rem 1rem;
                        margin-bottom:0.6rem; font-size:0.88rem;'>
                <div style='font-weight:bold; color:#003300; margin-bottom:0.2rem;'>
                    {title}
                </div>
                <div style='color:#333; line-height:1.6;'>{text}</div>
            </div>
            """, unsafe_allow_html=True)

    # ── Section 3: Early Warnings ──────────────────────────────────────────────
    st.markdown("### 3. Active Risk Flags")
    warnings = classification.get("early_warnings", [])
    if not warnings:
        st.success("No active risk flags. System operating within normal parameters.")
    else:
        sev_styles = {
            "CRITICAL": ("#FFEBEE", "#8B0000"),
            "ALERT":    ("#FFF3E0", "#E65100"),
            "WARNING":  ("#FFFDE7", "#C5A028"),
            "INFO":     ("#E3F2FD", "#1565C0"),
        }
        for w in warnings:
            bg, col = sev_styles.get(w["severity"], ("#F5F5F5", "#555"))
            st.markdown(f"""
            <div style='background:{bg}; border-left:4px solid {col};
                        padding:0.6rem 1rem; border-radius:4px; margin-bottom:0.5rem;
                        font-size:0.85rem;'>
                <b style='color:{col};'>{w["severity"]} — {w["flag"]}</b><br>
                <span style='color:#333;'>{w["plain_english"]}</span>
            </div>
            """, unsafe_allow_html=True)

    # ── Section 4: Policy Recommendations ─────────────────────────────────────
    st.markdown("### 4. Policy Recommendations")

    priority_action = signals.get("priority_action", {})
    if priority_action:
        pa_col = {"RATE_ACTION": "#8B0000", "RISK_FLAG": "#E65100",
                  "MONITORING": "#C5A028", "COORDINATION": "#1565C0",
                  "COMMUNICATION": "#006400"}.get(priority_action.get("type", ""), "#555")
        st.markdown(f"""
        <div style='background:{pa_col}18; border:2px solid {pa_col};
                    border-radius:8px; padding:1rem; margin-bottom:1rem;'>
            <div style='font-size:0.8rem; font-weight:bold; color:{pa_col};'>
                PRIORITY ACTION — {priority_action.get("type", "")}
            </div>
            <div style='font-size:1rem; font-weight:bold; color:{pa_col}; margin:0.3rem 0;'>
                {priority_action.get("action", "")}
            </div>
            <div style='font-size:0.88rem; color:#333;'>
                {priority_action.get("detail", "")}
            </div>
        </div>
        """, unsafe_allow_html=True)

    st.markdown("**All Recommended Actions:**")
    for i, sig in enumerate(signals.get("signals", []), 1):
        type_col = {"RATE_ACTION": "#8B0000", "RISK_FLAG": "#E65100",
                    "MONITORING": "#C5A028",  "COORDINATION": "#1565C0",
                    "COMMUNICATION": "#006400"}.get(sig["type"], "#555")
        st.markdown(f"""
        <div style='border-left:3px solid {type_col}; padding:0.5rem 1rem;
                    margin-bottom:0.5rem; font-size:0.85rem;'>
            <span style='color:{type_col}; font-weight:bold;'>
                {i}. [{sig["type"]}] {sig["action"]}
            </span><br>
            <span style='color:#444;'>{sig["detail"]}</span>
        </div>
        """, unsafe_allow_html=True)

    # ── Footer ─────────────────────────────────────────────────────────────────
    st.markdown("---")
    st.markdown(f"""
    <div style='text-align:center; font-size:0.72rem; color:#AAAAAA;
                border-top:1px solid #EEEEEE; padding-top:0.8rem;'>
        This memorandum was auto-generated by IRIS v1.0 on {loaded_at.strftime('%d %B %Y at %H:%M')}.
        It is a simulated educational document and does not represent an official CBK publication.
        Lead Scientist: Stephen Munene | Policy Analysis Unit, CBK
    </div>
    """, unsafe_allow_html=True)